# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manicurer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name_plural': 'Pictures'},
        ),
    ]
