# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicurer', '0002_auto_20180313_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='date_upload',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='image',
        ),
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
