# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicurer', '0006_delete_examplemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
