# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicurer', '0007_auto_20180314_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
    ]
