# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicurer', '0008_auto_20180314_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.CharField(max_length=100, null=True)),
                ('Context', models.CharField(max_length=100, null=True)),
                ('Speaker', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
