# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manicurer', '0010_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
    ]
